### ISSUE TITLE
Move syntax to a custom OOP syntax.

### ISSUE THREAD

**Issue by metatablecat** [metatablecat/Objective#1]
Currently, Objective follows a C++ syntax with its objects.

However, I've recently wanted to change the syntax to make it's own implementation to both improve readability and make it more like Lua instead of based off another language:

The ``public`` and ``private`` keyword will also let you pass access modifiers as seen in the example below

Example syntax would be
```lua
local class = Objective.class
local public = Objective.public
local private = Objective.private

local get = Objective.util.get
local set = Objective.util.set

local Cat = class "Cat" {
  [public "Name"] = {get = get, set = set}
}
```

I could also modify this to support typings in the near future:
```lua
local Cat = class "Cat" {
  [public ("Name," types.string)] = {get = get, set = set}
```

Final syntax change would be having an init pointer used to initialise objects and pass initial values (if not passed already)
```lua
[init] = function(self)
  self.Name == "Tamika"
end
```

Of course, any feedback will be welcome!

**Comment by metatablecat** [comment]
Another way to generate typings could be
```lua
[public "name"] = types.get("string")
```

**Comment by metatablecat** [comment]
https://github.com/metatablecat/Objective/tree/new-syntax-beta

**Comment by metatablecat** [comment]
This has now been merged into the main branch. You can access the old syntax under the branch ``discontinued-ccp-syntax``

**Comment by GnomeDevs** [comment]
sucks!!!!
